from django.db import models

from .artist import Artist
from .others import Track
from .user import User


class Playlist(models.Model):
    name = models.CharField(max_length=50)
    created_by_artist = models.ForeignKey(to=Artist, null=True, on_delete=models.CASCADE)
    created_by_user = models.ForeignKey(to=User, null=True, on_delete=models.CASCADE)
    description = models.CharField(max_length=5000)
    liked_by = models.ManyToManyField(User, through="PlaylistLikes")
    type = models.CharField(
        max_length=4, choices=[("AU", "AutoGenerated"), ("AR", "Artist"), ("US", "User"), ("CL", "Collaborative")]
    )
    track = models.ManyToManyField(Track, through="PlaylistContent")
    participant = models.ManyToManyField(User, through="PlaylistParticipants")
    visibility = models.CharField(
        max_length=4, choices=[("PB", "public"), ("PR", "private"), ("FW", "followers"), ("FR", "friends")]
    )


class PlaylistLikes(models.Model):
    liked_by = models.ForeignKey(to=User, on_delete=models.CASCADE)
    playlist = models.ForeignKey(to=Playlist, on_delete=models.CASCADE)


class PlaylistContent(models.Model):
    track = models.ForeignKey(to=Track, on_delete=models.CASCADE)
    added_by = models.ForeignKey(to=User, null=True, on_delete=models.CASCADE)
    playlist = models.ForeignKey(to=Playlist, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("track", "added_by")


class PlaylistParticipants(models.Model):
    playlist = models.ForeignKey(to=Playlist, on_delete=models.CASCADE)
    participant = models.ForeignKey(to=User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("playlist", "participant")
